FROM rust:1-slim as build

USER root

RUN USER=root cargo new --bin course_1

WORKDIR /course_1

COPY ./Cargo.lock ./Cargo.lock

COPY ./Cargo.toml ./Cargo.toml

RUN cargo build --release

RUN rm src/*.rs

COPY ./src ./src

RUN rm ./target/release/deps/course_1*

RUN cargo build --release

FROM rust:1-slim

ENV PING_LISTEN_PORT=80
# set the startup command to run your binary

COPY --from=build /course_1/target/release/course_1 .

CMD ["./course_1"]

