version: '3.7'
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - web-server
    networks:
      - front-network
  web-server:
    build:
      context: .
      dockerfile: Dockerfile.multi-stage
    restart: always
    deploy:
      replicas: 4
    environment:
      - PING_LISTEN_PORT=3000
    expose:
      - "3000"
    networks:
      - front-network
networks:
  front-network:
    driver: bridge
  